language: c++
install: sudo apt-getinstall -qq gfortran scons mpich2 openmpi
env:
 global:
  OMP_NUM_THREADS=4
  ASAGI=noasagi
  COMPILER=gnu
  ASSERTIONS=no
  LAYERS=0
 matrix:
  TARGET=debug ASSERTIONS=yes
  TARGET=release
  MPI=mpich2
  MPI=openmpi
  OPENMP=notasks
  OPENMP=noomp
  SCENARIO=darcy FLUX_SOLVER=upwind
  SCENARIO=darcy FLUX_SOLVER=upwind LAYERS=8
  SCENARIO=swe FLUX_SOLVER=llf_bath
  SCENARIO=swe

before_script: scons scenario=$DARCY compiler=$COMPILER target=$TARGET assertions=$ASSERTIONS mpi=$MPI openmp=$OPENMP asagi=$ASAGI layers=$LAYERS flux_solver=$FLUX_SOLVER -j2

script: echo "Hi!"
