language: c++
install: sudo apt-getinstall -qq gfortran scons mpich2 openmpi
env:
 global:
  OMP_NUM_THREADS=4
  ASAGI=noasagi
  COMPILER=gnu
 matrix:
  TARGET=debug
  TARGET=release
  MPI=mpich2
  MPI=openmpi
  OPENMP=notasks
  OPENMP=noomp

install: scons compiler=$COMPILER target=$TARGET mpi=$MPI openmp=$OPENMP asagi=$ASAGI -j2

script: echo "Hi!"
