language: c++
install: sudo apt-get install gfortran g77 scons mpich2 openmpi
env:
 global:
  OMP_NUM_THREADS=4
  ASAGI=noasagi
  COMPILER=gnu
 matrix:
  TARGET=debug
  TARGET=release
  MPI=mpich2
  MPI=openmpi
  OPENMP=notasks
  OPENMP=noomp

script: scons compiler=$COMPILER target=$TARGET mpi=$MPI openmp=$OPENMP asagi=$ASAGI -j2
