language: c++
install: sudo apt-get install gfortran g77 scons mpich2 openmpi
env:
 global:
  OMP_NUM_THREADS=4
 matrix:
  TARGET=debug
  TARGET=release
  MPI=mpich2
  MPI=openmpi
  OPENMP=notasks
  OPENMP=noomp

script: scons compiler=gnu target=$TARGET mpi=$MPI openmp=$OPENMP -j2
